// Generated by CoffeeScript 1.6.3
var Pusher, S3Pusher, cli, colors, version;

cli = require("./cli");

version = require('./utils/version');

Pusher = require("./pusher");

colors = require('colors');

S3Pusher = (function() {
  function S3Pusher() {
    var argv;
    argv = cli.argv;
    if (!argv.access_key || !argv.secret_key || !argv.bucket || !argv.directory) {
      console.log("\nMissing required fields:\n".red);
    }
    if (!argv.access_key) {
      console.log("* Access key required!\n".yellow);
    }
    if (!argv.secret_key) {
      console.log("* Secret key required!\n".yellow);
    }
    if (!argv.bucket) {
      console.log("* Bucket name required!\n".yellow);
    }
    if (!argv.directory) {
      console.log("* Source directory required!\n".yellow);
    }
    if (argv.version) {
      return console.log(version);
    } else if (argv.directory && argv.access_key && argv.secret_key) {
      this.pusher = new Pusher(argv.access_key, argv.secret_key, argv.bucket);
      return this.push(argv.directory);
    } else {
      console.log(cli.help());
    }
  }

  S3Pusher.prototype.push = function(dir) {
    var files;
    return files = this.pusher.push(dir);
  };

  return S3Pusher;

})();

module.exports = S3Pusher;
